language: node_js

node_js:
  - 12

install:
  - echo "in the installation process"

before_script:
  - echo "before running the building script"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - echo "Here we are building the image"
  - docker build -t udagram-api-feed:v1 .
  - docker tag udagram-api-feed:v1 muhammedismaildev/udagram-api-feed:v1
  # pushing the image to the docker reg
  - docker push muhammedismaildev/udagram-api-feed:v1
  - echo "image has been pushed"
