apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udagram-api-feed
  name: udagram-api-feed
spec:
  selector:
    matchLabels:
      service: udagram-api-feed
  replicas: 3
  template:
    metadata:
      labels:
        service: udagram-api-feed
    spec:
      containers:
        - image: muhammedismaildev/udagram-api-feed:v1
          name: udagram-api-feed
          imagePullPolicy: Always
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-configmap
          volumeMounts:
            - name: aws-config-volume
              mountPath: /root/.aws
      restartPolicy: Always

      volumes:
        - name: aws-config-volume
          secret:
            secretName: aws-secret

